name:                unsafe-ptr-maybe
version:             0.1.0.0
github:              "michaeljklein/unsafe-ptr-maybe"
license:             BSD3
author:              "Michael J. Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "(c) 2018 Michael J. Klein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaeljklein/unsafe-ptr-maybe#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-prim
- QuickCheck
- checkers

library:
  source-dirs: src

executables:
  unsafe-ptr-maybe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unsafe-ptr-maybe

tests:
  unsafe-ptr-maybe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unsafe-ptr-maybe
